#tipo de base de datos
quarkus.datasource.db-kind=mysql

#credenciales compartidas
quarkus.datasource.username=root
quarkus.datasource.password=mysql123

#esquema de generacion
quarkus.hibernate-orm.database.generation=update

