quarkus.application.name=ms-alumnos
quarkus.http.port=8081

#Base de dato propia del microservicio
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/bd_alumnos

mensaje.servicio= Microservicio de Alumnos