quarkus.application.name=ms-cursos
quarkus.http.port=8082

#Base de dato propia del microservicio
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/bd_cursos

mensaje.servicio= Microservicio de cursos