quarkus.config.locations=file:///C:/Users/jhons/Downloads/dad-quarkus-01-master/dad-ms-base/central-config/common.properties
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/ms_matriculas_db

quarkus.http.port=8083

# REST Clients config
# Omitimos /mp-rest/url si la ultima version usa otra sintaxis, pero con @RegisterRestClient(baseUri=...) se requiere esto en properties a veces,
# Quarkus usa: quarkus.rest-client."pe.edu.upeu.clients.AlumnoClient".url=http://localhost:8081
quarkus.rest-client."pe.edu.upeu.clients.AlumnoClient".url=http://localhost:8081
quarkus.rest-client."pe.edu.upeu.clients.CursoClient".url=http://localhost:8082
