quarkus.config.locations=file:///C:/Users/jhons/Downloads/dad-quarkus-01-master/dad-ms-base/central-config/common.properties,file:///C:/Users/jhons/Downloads/dad-quarkus-01-master/dad-ms-base/central-config/ms-cursos.properties
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/ms_cursos_db

quarkus.http.port=8082
